name: wvp

services:
  polaris-redis:
    image: redis:7.2
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - media-net
    ports:
      - 6379:6379
    volumes:
      - ./redis/conf/redis.conf:/opt/polaris/redis/redis.conf
      - ./volumes/redis/data/:/data
    environment:
      TZ: "Asia/Shanghai"
    command: redis-server /opt/polaris/redis/redis.conf --appendonly yes

  polaris-mysql:
    image: mysql:8.0
    healthcheck:
      test: [ "CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/3306" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - media-net
    environment:
      MYSQL_DATABASE: wvp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wvp
      MYSQL_PASSWORD: wvp
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./logs/mysql:/logs
      - ./volumes/mysql/data:/var/lib/mysql  
    command: [
          'mysqld',
          '--default-authentication-plugin=mysql_native_password',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_general_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]

  polaris-media:
    image: polaris-tian-docker.pkg.coding.net/qt/polaris/polaris-media:latest
    networks:
      - media-net
    ports:
      - "10000:10000/tcp"
      - "10000:10000/udp"
      - "10935:10935/tcp"
      - "10935:10935/udp"
      - "5540:5540/tcp"
      - "5540:5540/udp"
      - "6080:6080"
    volumes:
      - ./volumes/video:/opt/media/www/record/
      - ./logs/media:/opt/media/log/

  polaris-wvp:
    image: polaris-tian-docker.pkg.coding.net/qt/polaris/polaris-wvp:latest
    networks:
      - media-net
    ports:
      - "18978:18978"
      - "8116:8116/udp"
      - "8116:8116/tcp"
    depends_on:
      - polaris-redis
      - polaris-mysql
      - polaris-media
    volumes:
      - ./wvp/wvp/:/opt/wvp/
      - ./logs/wvp:/opt/wvp/logs/
    environment:
      TZ: "Asia/Shanghai"
      NGINX_HOST: http://127.0.0.1:8080

  polaris-nginx:
    image: polaris-tian-docker.pkg.coding.net/qt/polaris/polaris-nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - polaris-wvp
    links:
      - polaris-wvp
    environment:
      WVP_HOST: polaris-wvp
      WVP_PORT: 18978
    volumes:
      - ./nginx/dist:/opt/dist
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    networks:
      - media-net
      
networks:
  media-net:
    driver: bridge